export const FETCH_SHOPPINGCART_REQUEST = 'FETCH_SHOPPINGCART_REQUEST'
export const FETCH_SHOPPINGCART_SUCCESS = 'FETCH_SHOPPINGCART_SUCCESS'
export const FETCH_SHOPPINGCART_FAILURE = 'FETCH_SHOPPINGCART_FAILURE'
export const ADD_SHOPPINGCART_REQUEST = 'ADD_SHOPPINGCART_REQUEST'
export const GET_CART_BY_USER_ID = "GET_CART_BY_USER_ID";
