export const FETCH_PAYMENTS_REQUEST = "FETCH_PAYMENTS_REQUEST";
export const FETCH_PAYMENTS_SUCCESS = "FETCH_PAYMENTS_SUCCESS";
export const FETCH_PAYMENTS_FAILURE = "FETCH_PAYMENTS_FAILURE";
export const ADD_PAYMENT_REQUEST = "ADD_PAYMENT_REQUEST";
export const SEARCH_PAYMENTS_REQUEST = "SEARCH_PAYMENTS_REQUEST";
