export const FETCH_ROLES_REQUEST = "FETCH_ROLES_REQUEST";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILURE = "FETCH_ROLES_FAILURE";
export const DELETE_ROLE_REQUEST = "DELETE_ROLE_REQUEST";
export const UPDATE_ROLE_REQUEST = "UPDATE_ROLE_REQUEST";
export const ADD_ROLE_REQUEST = "ADD_ROLE_REQUEST";
export const SEARCH_ROLES_REQUEST = "SEARCH_ROLES_REQUEST";
