export const FETCH_ORDERITEMS_REQUEST = 'FETCH_ORDERITEMS_REQUEST'
export const FETCH_ORDERITEMS_SUCCESS = 'FETCH_ORDERITEMS_SUCCESS'
export const FETCH_ORDERITEMS_FAILURE = 'FETCH_ORDERITEMS_FAILURE'
export const ADD_ORDERITEMS_REQUEST = 'ADD_ORDERITEMS_REQUEST'