export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE'
export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST'
export const GET_ORDER_BY_USER_ID = "GET_ORDER_BY_USER_ID";