export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const SEARCH_USERS_REQUEST="SEARCH_USERS_REQUEST";