export const FETCH_SHOPPINGCARTITEM_REQUEST = 'FETCH_SHOPPINGCARTITEM_REQUEST'
export const FETCH_SHOPPINGCARTITEM_SUCCESS = 'FETCH_SHOPPINGCARTITEM_SUCCESS'
export const FETCH_SHOPPINGCARTITEM_FAILURE = 'FETCH_SHOPPINGCARTITEM_FAILURE'
export const ADD_SHOPPINGCARTITEM_REQUEST = 'ADD_SHOPPINGCARTITEM_REQUEST'

