export const FETCH_ADDRESSS_REQUEST = "FETCH_ADDRESSS_REQUEST";
export const FETCH_ADDRESSS_SUCCESS = "FETCH_ADDRESSS_SUCCESS";
export const FETCH_ADDRESSS_FAILURE = "FETCH_ADDRESSS_FAILURE";
export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST";
export const SEARCH_ADDRESSS_REQUEST="SEARCH_ADDRESSS_REQUEST";